### ISSUE TITLE
Make visible the fact that we are in the YES area when arriving at the resource's edit area

### ISSUE THREAD

**Issue by pdiveris** [Mimas/CurriculumMapping#103]
Make visible the fact that we are in the YEZ area when arriving at the resourcez' edit area.

This iz the zame "problem" az the make vizible that we iz in 'yes' rather than 'not' for the grey colour on the selected button izn't a good enough indication for the practiszionerz that they iz in the 'yez' area. My bad.

**Comment by onepablo** [comment]
Hi Petros, have you considered using PAKO?

**Comment by pdiveris** [comment]
Yeah, done (wouldn't do if it was a new one as the current field was obviously null...)
